// <auto-generated />
using System;
using AlexAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AlexAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240917154630_AddNumericFieldsToSpecification")]
    partial class AddNumericFieldsToSpecification
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlexAPI.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("is2FA")
                        .HasColumnType("bit");

                    b.Property<Guid>("secretKey2FA")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Auto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeamFeet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeamMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BedConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Builder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CabinConfig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cabins")
                        .HasColumnType("int");

                    b.Property<string>("CruisingSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Draft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftFeet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Engines")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelConsumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelConsumptionUnits")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestsSleeping")
                        .HasColumnType("int");

                    b.Property<string>("HullConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HullConstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthFeet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Superstructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCrew")
                        .HasColumnType("int");

                    b.Property<string>("Toys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<int>("YearRefit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Autos", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brokers", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Crew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("CrewPhotosSwitch")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Crews", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.CrewMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Tba")
                        .HasColumnType("bit");

                    b.Property<Guid?>("YachtBrochureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PhotoId");

                    b.HasIndex("YachtBrochureId");

                    b.ToTable("CrewMembers", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Gallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Galleries", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.GalleryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("GalleryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GalleryId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GalleryId2")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GalleryId3")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.HasIndex("GalleryId1");

                    b.HasIndex("GalleryId2");

                    b.HasIndex("GalleryId3");

                    b.ToTable("GalleryItems", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.General", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("DataSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GeneralDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Generals", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.KeyFeatureItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("YachtBrochureId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtBrochureId");

                    b.ToTable("KeyFeatures", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.LicenceRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<int>("LicenceId")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<Guid?>("YachtDetailGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtDetailGuid");

                    b.ToTable("LicenceRegistrations", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("YachtGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtGuid");

                    b.ToTable("Locations", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.OperatingAreaItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Areas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperatingAreaItems", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.OperatingAreaNew", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Areas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<Guid?>("YachtDetailGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtDetailGuid");

                    b.ToTable("OperatingAreaNews", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.OperatingAreas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("_25Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("_25Id");

                    b.ToTable("OperatingAreas", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<string>("Filename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFile")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Photos", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.PriceTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxRate")
                        .HasColumnType("int");

                    b.Property<int>("MinRate")
                        .HasColumnType("int");

                    b.Property<Guid?>("PricesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PricesId");

                    b.ToTable("PriceTerms", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Prices", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Prices", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Rate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaxRate")
                        .HasColumnType("int");

                    b.Property<int?>("MinRate")
                        .HasColumnType("int");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("Term")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("YachtDetailGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtDetailGuid");

                    b.ToTable("Rates", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.SpecialRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<string>("SpecialRequests")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("YachtDetailGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("YachtDetailGuid");

                    b.ToTable("SpecialRequest", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Specifications", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Beam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeamMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Builder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Cabins")
                        .HasColumnType("int");

                    b.Property<string>("CaptainsNationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrewProfiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CruisingSpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DoubleBeds")
                        .HasColumnType("int");

                    b.Property<int>("DoubleCabins")
                        .HasColumnType("int");

                    b.Property<string>("Draft")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExteriorDesigner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelCapacity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelConsumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GrossTonnage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrossTonnageNumeric")
                        .HasColumnType("int");

                    b.Property<int>("GuestsCruising")
                        .HasColumnType("int");

                    b.Property<int>("GuestsSleeping")
                        .HasColumnType("int");

                    b.Property<bool>("GymEquipment")
                        .HasColumnType("bit");

                    b.Property<string>("InteriorDesigner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KingBeds")
                        .HasColumnType("int");

                    b.Property<string>("Length")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthMetres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaxSpeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MaxSpeedNumeric")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Port")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropulsionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PullmanBeds")
                        .HasColumnType("int");

                    b.Property<int>("QueenBeds")
                        .HasColumnType("int");

                    b.Property<string>("RegistryPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SailPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SingleBeds")
                        .HasColumnType("int");

                    b.Property<string>("TotalPowerOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Toys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TwinCabins")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<int>("YearRefit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Specifications", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("VideoBrokerFriendly")
                        .HasColumnType("bit");

                    b.Property<string>("VideoId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoInfoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VideoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("VideoInfoId");

                    b.ToTable("Videos", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.VideoInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ChannelTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("VideoInfos", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.Yacht", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrochureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DetailGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistryPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Guid");

                    b.HasIndex("BrochureId");

                    b.HasIndex("DetailGuid");

                    b.HasIndex("UserId");

                    b.ToTable("Yachts", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.YachtBrochure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AutoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BrokerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CrewId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GalleriesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("GeneralId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OperatingAreasId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PricesId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecificationsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("VideoId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AutoId");

                    b.HasIndex("BrokerId");

                    b.HasIndex("CrewId");

                    b.HasIndex("GalleriesId");

                    b.HasIndex("GeneralId");

                    b.HasIndex("OperatingAreasId");

                    b.HasIndex("PricesId");

                    b.HasIndex("SpecificationsId");

                    b.HasIndex("VideoId");

                    b.ToTable("Brochures", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.YachtDetail", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AvFacilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AwardNominations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeamImperial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeamMetric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Beds")
                        .HasColumnType("int");

                    b.Property<string>("Builder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BulkBeds")
                        .HasColumnType("int");

                    b.Property<int>("Cabins")
                        .HasColumnType("int");

                    b.Property<string>("Captain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CaptainsNationality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Chef")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiefEngineer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChiefStewardess")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommercialStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Communications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contracts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConvertibleCabins")
                        .HasColumnType("int");

                    b.Property<DateTime>("CrewModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("CrewProfiles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CruisingSpeed")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateWentPublic")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoubleBeds")
                        .HasColumnType("int");

                    b.Property<int>("DoubleCabins")
                        .HasColumnType("int");

                    b.Property<string>("DraftImperial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DraftMetric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnginesGenerators")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Equipment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuelConsumption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GrossTons")
                        .HasColumnType("int");

                    b.Property<string>("GuestsAccommodation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GuestsCruising")
                        .HasColumnType("int");

                    b.Property<int>("GuestsSleeping")
                        .HasColumnType("int");

                    b.Property<string>("HullConfiguration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HullConstruction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("IndependentStakeholder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InteriorDesigner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KingBeds")
                        .HasColumnType("int");

                    b.Property<string>("LengthImperial")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LengthMetric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ListingType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationDet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MasterCabinOnMainDeck")
                        .HasColumnType("int");

                    b.Property<int>("MaxSpeed")
                        .HasColumnType("int");

                    b.Property<int>("MybaTippingPolicy")
                        .HasColumnType("int");

                    b.Property<string>("NavalArchitect")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperatingAreas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtherBuilder")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerCaOperated")
                        .HasColumnType("int");

                    b.Property<int>("OwnerCaptainOperated")
                        .HasColumnType("int");

                    b.Property<string>("PreviousName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PullmanBeds")
                        .HasColumnType("int");

                    b.Property<int>("QueenBeds")
                        .HasColumnType("int");

                    b.Property<string>("Range")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RateDet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefitDet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistryPort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rig")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SailPower")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeasonsUnavailable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SingleBeds")
                        .HasColumnType("int");

                    b.Property<int>("SingleCabins")
                        .HasColumnType("int");

                    b.Property<string>("SpecialConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummerBasePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SummerRates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Superstructure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxComments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalCrew")
                        .HasColumnType("int");

                    b.Property<string>("Toys")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TripleCabins")
                        .HasColumnType("int");

                    b.Property<int>("TwinCabins")
                        .HasColumnType("int");

                    b.Property<string>("WinterBasePort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WinterRates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YachtAdmin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YachtAdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YachtAdminPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YachtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.Property<int?>("YearRefit")
                        .HasColumnType("int");

                    b.HasKey("Guid");

                    b.ToTable("Details", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AlexAPI.Models.CrewMember", b =>
                {
                    b.HasOne("AlexAPI.Models.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");

                    b.HasOne("AlexAPI.Models.YachtBrochure", null)
                        .WithMany("CrewMembers")
                        .HasForeignKey("YachtBrochureId");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("AlexAPI.Models.GalleryItem", b =>
                {
                    b.HasOne("AlexAPI.Models.Gallery", null)
                        .WithMany("Full")
                        .HasForeignKey("GalleryId");

                    b.HasOne("AlexAPI.Models.Gallery", null)
                        .WithMany("Interior")
                        .HasForeignKey("GalleryId1");

                    b.HasOne("AlexAPI.Models.Gallery", null)
                        .WithMany("Layout")
                        .HasForeignKey("GalleryId2");

                    b.HasOne("AlexAPI.Models.Gallery", null)
                        .WithMany("Pdf")
                        .HasForeignKey("GalleryId3");
                });

            modelBuilder.Entity("AlexAPI.Models.KeyFeatureItem", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtBrochure", null)
                        .WithMany("KeyFeatures")
                        .HasForeignKey("YachtBrochureId");
                });

            modelBuilder.Entity("AlexAPI.Models.LicenceRegistration", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtDetail", null)
                        .WithMany("LicencesRegistrations")
                        .HasForeignKey("YachtDetailGuid");
                });

            modelBuilder.Entity("AlexAPI.Models.Location", b =>
                {
                    b.HasOne("AlexAPI.Models.Yacht", null)
                        .WithMany("Locations")
                        .HasForeignKey("YachtGuid");
                });

            modelBuilder.Entity("AlexAPI.Models.OperatingAreaNew", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtDetail", null)
                        .WithMany("OperatingAreasNew")
                        .HasForeignKey("YachtDetailGuid");
                });

            modelBuilder.Entity("AlexAPI.Models.OperatingAreas", b =>
                {
                    b.HasOne("AlexAPI.Models.OperatingAreaItem", "_25")
                        .WithMany()
                        .HasForeignKey("_25Id");

                    b.Navigation("_25");
                });

            modelBuilder.Entity("AlexAPI.Models.PriceTerm", b =>
                {
                    b.HasOne("AlexAPI.Models.Prices", null)
                        .WithMany("_25")
                        .HasForeignKey("PricesId");
                });

            modelBuilder.Entity("AlexAPI.Models.Rate", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtDetail", null)
                        .WithMany("Rates")
                        .HasForeignKey("YachtDetailGuid");
                });

            modelBuilder.Entity("AlexAPI.Models.SpecialRequest", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtDetail", null)
                        .WithMany("SpecialRequests")
                        .HasForeignKey("YachtDetailGuid");
                });

            modelBuilder.Entity("AlexAPI.Models.Video", b =>
                {
                    b.HasOne("AlexAPI.Models.VideoInfo", "VideoInfo")
                        .WithMany()
                        .HasForeignKey("VideoInfoId");

                    b.Navigation("VideoInfo");
                });

            modelBuilder.Entity("AlexAPI.Models.Yacht", b =>
                {
                    b.HasOne("AlexAPI.Models.YachtBrochure", "Brochure")
                        .WithMany()
                        .HasForeignKey("BrochureId");

                    b.HasOne("AlexAPI.Models.YachtDetail", "Detail")
                        .WithMany()
                        .HasForeignKey("DetailGuid");

                    b.HasOne("AlexAPI.Authentication.ApplicationUser", null)
                        .WithMany("Companies")
                        .HasForeignKey("UserId");

                    b.Navigation("Brochure");

                    b.Navigation("Detail");
                });

            modelBuilder.Entity("AlexAPI.Models.YachtBrochure", b =>
                {
                    b.HasOne("AlexAPI.Models.Auto", "Auto")
                        .WithMany()
                        .HasForeignKey("AutoId");

                    b.HasOne("AlexAPI.Models.Broker", "Broker")
                        .WithMany()
                        .HasForeignKey("BrokerId");

                    b.HasOne("AlexAPI.Models.Crew", "Crew")
                        .WithMany()
                        .HasForeignKey("CrewId");

                    b.HasOne("AlexAPI.Models.Gallery", "Galleries")
                        .WithMany()
                        .HasForeignKey("GalleriesId");

                    b.HasOne("AlexAPI.Models.General", "General")
                        .WithMany()
                        .HasForeignKey("GeneralId");

                    b.HasOne("AlexAPI.Models.OperatingAreas", "OperatingAreas")
                        .WithMany()
                        .HasForeignKey("OperatingAreasId");

                    b.HasOne("AlexAPI.Models.Prices", "Prices")
                        .WithMany()
                        .HasForeignKey("PricesId");

                    b.HasOne("AlexAPI.Models.Specifications", "Specifications")
                        .WithMany()
                        .HasForeignKey("SpecificationsId");

                    b.HasOne("AlexAPI.Models.Video", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId");

                    b.Navigation("Auto");

                    b.Navigation("Broker");

                    b.Navigation("Crew");

                    b.Navigation("Galleries");

                    b.Navigation("General");

                    b.Navigation("OperatingAreas");

                    b.Navigation("Prices");

                    b.Navigation("Specifications");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AlexAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AlexAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AlexAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AlexAPI.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AlexAPI.Authentication.ApplicationUser", b =>
                {
                    b.Navigation("Companies");
                });

            modelBuilder.Entity("AlexAPI.Models.Gallery", b =>
                {
                    b.Navigation("Full");

                    b.Navigation("Interior");

                    b.Navigation("Layout");

                    b.Navigation("Pdf");
                });

            modelBuilder.Entity("AlexAPI.Models.Prices", b =>
                {
                    b.Navigation("_25");
                });

            modelBuilder.Entity("AlexAPI.Models.Yacht", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("AlexAPI.Models.YachtBrochure", b =>
                {
                    b.Navigation("CrewMembers");

                    b.Navigation("KeyFeatures");
                });

            modelBuilder.Entity("AlexAPI.Models.YachtDetail", b =>
                {
                    b.Navigation("LicencesRegistrations");

                    b.Navigation("OperatingAreasNew");

                    b.Navigation("Rates");

                    b.Navigation("SpecialRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
