name: Build and deploy ASP.Net Core app to FTPS - YachtShopAPI

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish
        run: dotnet publish ./AlexAPI.sln --configuration Release --no-build --output './publish'

      - name: Upload Publish Directory
        uses: actions/upload-artifact@v3
        with:
          name: publish
          path: './publish'
          retention-days: 3

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
      - name: Download Publish Directory
        uses: actions/download-artifact@v3
        with:
          name: publish
          path: './publish'

      - name: Upload files to FTPS
        env:
          FTP_USERNAME: u118215671
          FTP_PASSWORD: ${{ secrets.FTP }}
        run: |
          find ./publish -type f | xargs -I {} curl --ftp-ssl --ftp-ssl-reqd -v \
            --user "$FTP_USERNAME:$FTP_PASSWORD" \
            --upload-file "{}" \
            "ftps://access1024699194.webspace-data.io:990/API/"
        shell: bash
